[package]
name = "env_config"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_config_derive = { path = "../env_config_derive" }


[dev-dependencies]
assert2 = "0.3.6"
temp-env = "0.2.0"
